# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution_name', models.CharField(max_length=100)),
                ('accreditation_level', models.IntegerField()),
                ('license_for_educational_activity', models.TextField()),
                ('founding_date', models.DateField()),
            ],
            options={
                'db_table': 'educational_institution',
            },
        ),
    ]
