# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0002_auto_20170506_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_institution_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.City'),
        ),
        migrations.AddField(
            model_name='educational_institution',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.Educational_institution_type'),
        ),
    ]
