# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0003_auto_20170506_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_direction_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'educational_direction',
            },
        ),
        migrations.CreateModel(
            name='Educational_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_method_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'educational_method',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('average_mark', models.FloatField()),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Type_of_payment_for_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_payment_for_education', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type_of_payment_for_education',
            },
        ),
        migrations.RenameField(
            model_name='educational_institution',
            old_name='type',
            new_name='educational_institution_type',
        ),
        migrations.AlterModelTable(
            name='educational_institution_type',
            table='educational_institution_type',
        ),
    ]
