# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0004_auto_20170506_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educational_institution',
            old_name='educational_institution_type',
            new_name='type',
        ),
    ]
