# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0005_auto_20170506_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='educational_institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.Educational_institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.City'),
        ),
    ]
