# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0008_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_institution',
            name='accreditation_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Accreditation level'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='educational_institution_name',
            field=models.CharField(max_length=100, verbose_name='Name of the educational institution'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Founding date'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='license_for_educational_activity',
            field=models.TextField(blank=True, default='', null=True, verbose_name='License for educational activity'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.Educational_institution_type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='educational_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.Educational_institution', verbose_name='Educational institution'),
        ),
    ]
