# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0009_auto_20170507_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=100, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='educational_direction',
            name='educational_direction_name',
            field=models.CharField(max_length=100, verbose_name='Educational direction name'),
        ),
        migrations.AlterField(
            model_name='educational_direction',
            name='educational_institution',
            field=models.ManyToManyField(blank=True, null=True, to='educational_institution.Educational_institution', verbose_name='Educational institution'),
        ),
        migrations.AlterField(
            model_name='educational_institution_type',
            name='educational_institution_type',
            field=models.CharField(max_length=100, verbose_name='Type of Educational institution'),
        ),
        migrations.AlterField(
            model_name='educational_method',
            name='educational_institution',
            field=models.ManyToManyField(blank=True, null=True, to='educational_institution.Educational_institution', verbose_name='Educational institution'),
        ),
        migrations.AlterField(
            model_name='educational_method',
            name='educational_method_name',
            field=models.CharField(max_length=100, verbose_name='Educational method name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=100, verbose_name='Faculty name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='average_mark',
            field=models.FloatField(blank=True, null=True, verbose_name='Average mark'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institution.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ManyToManyField(blank=True, null=True, to='educational_institution.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, verbose_name='Student name'),
        ),
        migrations.AlterField(
            model_name='type_of_payment_for_education',
            name='educational_institution',
            field=models.ManyToManyField(blank=True, null=True, to='educational_institution.Educational_institution', verbose_name='Educational institution'),
        ),
        migrations.AlterField(
            model_name='type_of_payment_for_education',
            name='type_of_payment_for_education',
            field=models.CharField(max_length=100, verbose_name='Type of payment for education'),
        ),
    ]
