# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0010_auto_20170507_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational_direction',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='educational_method',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='type_of_payment_for_education',
            name='educational_institution',
        ),
        migrations.AddField(
            model_name='educational_institution',
            name='educational_direction',
            field=models.ManyToManyField(blank=True, to='educational_institution.Educational_direction', verbose_name='Educational direction'),
        ),
        migrations.AddField(
            model_name='educational_institution',
            name='educational_method',
            field=models.ManyToManyField(blank=True, to='educational_institution.Educational_method', verbose_name='Educational method'),
        ),
        migrations.AddField(
            model_name='educational_institution',
            name='type_of_payment_for_education',
            field=models.ManyToManyField(blank=True, to='educational_institution.Type_of_payment_for_education', verbose_name='Type of payment for education'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='educational_institution.Faculty', verbose_name='Faculty'),
        ),
    ]
