# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0011_auto_20170507_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_institution',
            name='educational_direction',
            field=models.ManyToManyField(blank=True, related_name='educational_direction', to='educational_institution.Educational_direction', verbose_name='Educational direction'),
        ),
        migrations.AlterField(
            model_name='educational_institution',
            name='educational_method',
            field=models.ManyToManyField(blank=True, related_name='educational_method', to='educational_institution.Educational_method', verbose_name='Educational method'),
        ),
    ]
