# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_institution', '0012_auto_20170507_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_institution',
            name='type_of_payment_for_education',
            field=models.ManyToManyField(blank=True, related_name='payment_type', to='educational_institution.Type_of_payment_for_education', verbose_name='Type of payment for education'),
        ),
    ]
